# Generated by Django 4.2.6 on 2023-10-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_aboba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboba',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='feedback.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='feedback.users'),
        ),
    ]
