# Generated by Django 4.2.6 on 2023-10-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_users_lead_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='feedback.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='feedback.users')),
            ],
        ),
    ]
