# Generated by Django 4.2.6 on 2023-10-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='user_id',
            new_name='user',
        ),
    ]
