# Generated by Django 4.2.6 on 2023-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='subjectivity',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
